config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    collection do
      get :add_email
      patch :signup_email
    end
  end

  root to: 'questions#index'

  concern :ratingable do
    member do
      post :vote_up
      post :vote_down
      post :vote_reset
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :attachments, only: :destroy
  resources :questions, except: [:edit], concerns: [:ratingable, :commentable] do
    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:ratingable, :commentable] do
      member do
        patch :select_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :search, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  include Ratingable
  include Commentable
  include Subscribable

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable

  belongs_to :user

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: :show

  authorize_resource

  def index
    respond_with(Question.order(:created_at))
  end

  def show
    respond_with(@question, serializer: QuestionShowSerializer)
  end

  def create
    current_user.questions.create(question_params)
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Ratinged

  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_question, only: :show
  before_action :find_current_user_question, only: [:destroy, :update]
  after_action :publish_question, only: :create

  authorize_resource

  def index
    @questions = Question.all
  end

  def new
    @question = current_user.questions.build
    @question.attachments.build
  end

  def show
    @answers = @question.answers.by_best
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: 'Question create successfully'
    else
      render :new
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question successfully deleted'
  end

  def update
    @question.update(question_params)
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions', question: @question)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_current_user_question
    @question = current_user.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
li.collection-item
  div
    = link_to question.title, question
    - if can?(:destroy, question)
      = link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are you sure?' }, class: 'secondary-content'

app/views/questions/_question_block.html.slim
.question_errors
div class="question_#{question.id} question" data-id="#{question.id}"
  .row
    .col.s12.m12
      .card
        .card-content
          - cache question do
            span.card-title = question.title
            p = question.body
          = render 'shared/rating', resource: question
          ul
            - question.attachments.each do |a|
              - cache a do
                li id="attachment_#{a.id}"
                  i class="material-icons" attach_file
                  = link_to a.file.identifier, a.file.url
              - if can?(:destroy, a)
                = link_to 'Remove file', attachment_path(a), method: :delete, data: { confirm: 'are you sure?', remote: true }
          .card-action
            - if can?(:update, question)
              p= link_to 'Edit', '', class: 'edit-question-link', data: { question_id: question.id }
              p
                = form_with model: question, id: "edit-question-#{question.id}", class: 'edit_question' do |f|
                  .input-field.col.s12
                    = f.text_field :title
                    = f.label :title
                  .input-field.col.s12
                    = f.text_area :body, class: 'materialize-textarea'
                    = f.label :body
                  = f.submit 'Save', class: 'btn'
            .right
              - if can?(:create, Subscription)
                - if question.subscribed?(current_user)
                  = link_to subscription_path(question.subscribed?(current_user)), method: :delete do
                    | Unsubscribe
                    i.material-icons.right notifications
                - else
                  = link_to question_subscriptions_path(question), method: :post do
                    | Subscribe
                    i.material-icons.right notifications_none
  h5.center Comments
  div class="comment_#{question.class}_#{question.id}"
    p
      = render question.comments
    p
      = render 'comments/form', resource: question

app/views/questions/index.html.slim
- if can?(:create, Question)
  = link_to 'Ask question', new_question_path, class: 'btn'

ul.collection.with-header.questions-index
  li.collection-header
    h4 Questions
  = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |form|
  .input-field.col.s12
    = form.text_field :title
    = form.label :title
  .input-field.col.s12
    = form.text_area :body, class: 'materialize-textarea'
    = form.label :body

  #attachments
    = form.fields_for :attachments do |attachment|
      = render 'attachments/attachment_fields', f: attachment

      = link_to_add_association 'Add attachment', form, :attachments, partial: 'attachments/attachment_fields'

  = form.submit class: 'btn'

app/views/questions/show.html.slim
= render 'question_block', question: @question
h4 Answers
.answers
  - if @answers.present?
    = render @answers
  - else
    p No answers here
- if can?(:create, Answer)
  h5 New Answer
  #answer_errors
  = form_with model: [@question, @answer], class: 'new_answer_form' do |form|

    = render 'shared/errors', resource: @answer

    = form.label :body
    = form.text_field :body

    #attachments
      = form.fields_for :attachments do |attachment|
        = render 'attachments/attachment_fields', f: attachment
        = link_to_add_association 'Add attachment', form, :attachments, partial: 'attachments/attachment_fields'
    br
    = form.submit class: 'btn'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $('#question_errors').html('<%= j render "shared/errors", resource: @question %>');
<% else %>
  $('.question_<%= @question.id %>').replaceWith('<%= j render "question_block", question: @question %>');
<% end %>