config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    collection do
      get :add_email
      patch :signup_email
    end
  end

  root to: 'questions#index'

  concern :ratingable do
    member do
      post :vote_up
      post :vote_down
      post :vote_reset
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :attachments, only: :destroy
  resources :questions, except: [:edit], concerns: [:ratingable, :commentable] do
    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:ratingable, :commentable] do
      member do
        patch :select_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :search, only: :index
end

app/models/search.rb
class Search < ApplicationRecord
  CATEGORIES = %w(Questions Users Answers Comments)

  def self.find(query, category)
    query = ThinkingSphinx::Query.escape(query) if query.present?
    if CATEGORIES.include?(category)
      category.classify.constantize.search(query)
    else
      ThinkingSphinx.search(query)
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    query = params[:query]
    category = params[:category]
    @resources = Search.find(query, category)
  end
end

app/views/search/index.html.slim
.row
  = form_tag search_index_path, method: :get, class: 'col s12' do
    .row
      .col.s6
        .input-field
          i.material-icons.prefix search
          = label_tag 'query', 'Search'
          = text_field_tag :query, params[:query]
      .col.s6
        .input-field.col.s12
          = select_tag :category, options_for_select(Search::CATEGORIES, selected: params[:category]), { prompt: "All", class: 'browser-default'}
    = button_tag 'Search', class: 'btn '
.search
  - if @resources.present?
    - @resources.each do |resource|
      .row
        .col.s12
          .card.blue-grey.darken-1
            .card-content.white-text
              - case resource.class.to_s
              - when 'Question'
                span.card-title = link_to resource.title, resource
              - when 'User', 'Admin'
                span.card-title = resource.email
              - when 'Answer'
                span.card-title  = link_to resource.body, resource.question
              - when 'Comment'
                - if resource.commentable.is_a?(Answer)
                  span.card-title  = link_to resource.body, resource.commentable.question
                - else
                  span.card-title  = link_to resource.body, resource.commentable
              p = resource.class.to_s
  - else
    h4.center.red-text = "No results found for #{params[:query]}."