config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :users, only: [] do
    collection do
      get :add_email
      patch :signup_email
    end
  end

  root to: 'questions#index'

  concern :ratingable do
    member do
      post :vote_up
      post :vote_down
      post :vote_reset
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :attachments, only: :destroy
  resources :questions, except: [:edit], concerns: [:ratingable, :commentable] do
    resources :answers, only: [:create, :destroy, :update], shallow: true, concerns: [:ratingable, :commentable] do
      member do
        patch :select_best
      end
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :search, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Ratingable
  include Commentable

  has_many :attachments, as: :attachable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, presence: true

  scope :by_best, -> { order(best: :desc, created_at: :desc) }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  after_commit :subscribers_notification, on: :create

  def select_best
    old_best = question.answers.find_by(best: true)

    transaction do
      old_best.update!(best: false) if old_best
      update!(best: true)
    end
  end

  def subscribers_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Ratinged

  before_action :authenticate_user!
  before_action :find_answer, only: :select_best
  before_action :find_question, only: :create
  before_action :find_current_user_answer, only: [:destroy, :update]
  after_action :publish_answer, only: :create

  authorize_resource

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @answer.destroy
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def select_best
    @answer.select_best
  end

  private

  def publish_answer
    return if @answer.errors.any?
    attachments = @answer.attachments.map do |a|
      { id: a.id, url: a.file.url, name: a.file.identifier }
    end
    ActionCable.server.broadcast(
      "answers_for_question_#{@answer.question_id}",
      answer: @answer, attachments: attachments,
      question_user_id: @answer.question.user_id
    )
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file, :id, :_destroy])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_current_user_answer
    @answer = current_user.answers.find(params[:id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [:index, :create]
  before_action :find_answer, only: :show

  authorize_resource

  def index
    respond_with(@question.answers)
  end

  def show
    respond_with(@answer, serializer: AnswerShowSerializer)
  end

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    @answer.save
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
  div class="answer_#{answer.id} best_#{answer.best}"
    .answer.card.blue-grey.darken-1
      .card-content.white-text
        - if answer.best?
          span.badge.green.white-text.answer-best-badge best
        - cache answer do
          p.answer-body = answer.body
        br = render 'shared/rating', resource: answer
      ul
        - answer.attachments.each do |a|
          - cache a do
            li id="attachment_#{a.id}"
              i class="material-icons" attach_file
              = link_to a.file.identifier, a.file.url
          - if can?(:destroy, a)
            = link_to 'Remove file', attachment_path(a), method: :delete, data: { confirm: 'are you sure?', remote: true }
      .card-action
        - if can?(:select_best, answer)
          = link_to 'Choose best', select_best_answer_path(answer), method: :patch, remote: true
        - if can?(:destroy, answer)
          = link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: 'are you sure?', remote: true }
        - if can?(:update, answer)
          = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
          = form_with model: answer, id: "edit-answer-#{answer.id}", class: 'edit_answer' do |f|
            .input-field.col.s12
              = f.text_area :body, class: 'materialize-textarea'
              = f.label :body, "Answer"
            = f.submit 'Save', class: 'btn'

    div class="comment_#{answer.class}_#{answer.id}"
      = render answer.comments
      = render 'comments/form', resource: answer

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  $('#answer_errors').html('<%= j render "shared/errors", resource: @answer %>');
<% else %>
  $('.answers').prepend('<%= j render @answer %>');
  $(".new_answer_form #answer_body").val('');
  $(".nested-fields").remove();
  $('#answer_errors').html('');
<% end %>

app/views/answers/destroy.js.erb
$('.answer_<%= @answer.id %>').remove();

app/views/answers/select_best.js.erb
<% if flash.present? %>
  $('.flash').html('<%= j render "shared/flash" %>');
<% else %>
  $('.answers').html('<%= j render @answer.question.answers.by_best %>');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  $('#answer_errors').html('<%= j render "shared/errors", resource: @answer %>');
<% else %>
  $('.answer_<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  $('#answer_errors').html('');
<% end %>